In [2]:
import torch
import torch.nn as nn
import tensorflow as tf
import tensorflow_addons as tfa




In [38]:
##ex code using marginrankingloss (pytorch) --> pairwise LF
input_one = torch.randn(3, requires_grad=True)
input_two = torch.randn(3, requires_grad=True)
target = torch.randn(3).sign()

ranking_loss = nn.MarginRankingLoss()
output = ranking_loss(input_one, input_two, target)
output.backward()

print('input one: ', input_one)
print('input two: ', input_two)
print('target: ', target)
print('output: ', output)

print(type(torch.dot(-target,input_one-input_two)))
##def class based on marginrankingloss

#note to self: according to documentation I found, marginrankingloss does 
#ouput a tensor
class my_margin_ranking_loss():

    def __init__(self, margin=0.0) -> None:
        #put margin into form can be accessed by other methods
        self.margin = margin

    def forward(self, input1, input2, target):
        #equation from marginrankingloss documentation
        # return torch.max(torch.tensor([0]),-target*(input1-input2)+self.margin)
        # return torch.max(torch.constant([0]),torch.dot(-target,input1-input2)+self.margin)
        my_dist = torch.dot(-target,input1-input2)

        #turn tensor into scalar
        scalar_dist = my_dist.item()
        return max(0,int(scalar_dist+self.margin))

    def forward(self, input1, input2, target):
        #equation from marginrankingloss documentation
        # return torch.max(torch.tensor([0]),-target*(input1-input2)+self.margin)
        # return torch.max(torch.constant([0]),torch.dot(-target,input1-input2)+self.margin)
        my_dist = torch.dot(-target,input1-input2)

        #turn tensor into scalar
        scalar_dist = my_dist.item()
        return max(0,int(scalar_dist+self.margin))

# return torch.max(torch.zeros(input1.size()),-target*(input1-input2)+torch.full(self.margin))


ranking_loss = my_margin_ranking_loss()
output = ranking_loss.forward(input_one, input_two, target)
output.backward()

print('input one: ', input_one)
print('input two: ', input_two)
print('target: ', target)
print('output: ', output)



input one:  tensor([-0.6842, -1.3532,  2.3002], requires_grad=True)
input two:  tensor([-0.4707, -0.0685,  0.3754], requires_grad=True)
target:  tensor([-1.,  1.,  1.])
output:  tensor(0.4282, grad_fn=<MeanBackward0>)
<class 'torch.Tensor'>


AttributeError: 'int' object has no attribute 'backward'

In [4]:
class MarginRankingLoss(_Loss):
    r"""Creates a criterion that measures the loss given
    inputs :math:`x1`, :math:`x2`, two 1D mini-batch or 0D `Tensors`,
    and a label 1D mini-batch or 0D `Tensor` :math:`y` (containing 1 or -1).
    If :math:`y = 1` then it assumed the first input should be ranked higher
    (have a larger value) than the second input, and vice-versa for :math:`y = -1`.
    The loss function for each pair of samples in the mini-batch is:
    .. math::
        \text{loss}(x1, x2, y) = \max(0, -y * (x1 - x2) + \text{margin})
    Args:
        margin (float, optional): Has a default value of :math:`0`.
        size_average (bool, optional): Deprecated (see :attr:`reduction`). By default,
            the losses are averaged over each loss element in the batch. Note that for
            some losses, there are multiple elements per sample. If the field :attr:`size_average`
            is set to ``False``, the losses are instead summed for each minibatch. Ignored
            when :attr:`reduce` is ``False``. Default: ``True``
        reduce (bool, optional): Deprecated (see :attr:`reduction`). By default, the
            losses are averaged or summed over observations for each minibatch depending
            on :attr:`size_average`. When :attr:`reduce` is ``False``, returns a loss per
            batch element instead and ignores :attr:`size_average`. Default: ``True``
        reduction (str, optional): Specifies the reduction to apply to the output:
            ``'none'`` | ``'mean'`` | ``'sum'``. ``'none'``: no reduction will be applied,
            ``'mean'``: the sum of the output will be divided by the number of
            elements in the output, ``'sum'``: the output will be summed. Note: :attr:`size_average`
            and :attr:`reduce` are in the process of being deprecated, and in the meantime,
            specifying either of those two args will override :attr:`reduction`. Default: ``'mean'``
    Shape:
        - Input1: :math:`(N)` or :math:`()` where `N` is the batch size.
        - Input2: :math:`(N)` or :math:`()`, same shape as the Input1.
        - Target: :math:`(N)` or :math:`()`, same shape as the inputs.
        - Output: scalar. If :attr:`reduction` is ``'none'`` and Input size is not :math:`()`, then :math:`(N)`.
    Examples::
        >>> loss = nn.MarginRankingLoss()
        >>> input1 = torch.randn(3, requires_grad=True)
        >>> input2 = torch.randn(3, requires_grad=True)
        >>> target = torch.randn(3).sign()
        >>> output = loss(input1, input2, target)
        >>> output.backward()
    """
    __constants__ = ['margin', 'reduction']
    margin: float

    def __init__(self, margin: float = 0., size_average=None, reduce=None, reduction: str = 'mean') -> None:
        super(MarginRankingLoss, self).__init__(size_average, reduce, reduction)
        self.margin = margin

    def forward(self, input1: Tensor, input2: Tensor, target: Tensor) -> Tensor:
        return F.margin_ranking_loss(input1, input2, target, margin=self.margin, reduction=self.reduction)

NameError: name '_Loss' is not defined

In [5]:
##ex code using marginrankingloss (pytorch) --> pairwise LF
input_one = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]], dtype=torch.float16,requires_grad=True)
input_two = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]], dtype=torch.float16,requires_grad=True)
target = torch.randn(1)

ranking_loss = nn.MarginRankingLoss()
output = ranking_loss(input_one, input_two, target)
output.backward()

print('input one: ', input_one)
print('input two: ', input_two)
print('target: ', target)
print('output: ', output)

input one:  tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16, requires_grad=True)
input two:  tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16, requires_grad=True)
target:  tensor([-0.3481])
output:  tensor(0., grad_fn=<MeanBackward0>)


In [1]:
##def class based on marginrankingloss

#note to self: according to documentation I found, marginrankingloss does 
#ouput a tensor
class my_margin_ranking_loss():

    def __init__(self, margin=0.0) -> None:
        #put margin into form can be accessed by other methods
        self.margin = margin

    def forward(self, input1, input2, target):
        #equation from marginrankingloss documentation
        return torch.max(0,-target*(input1-input2)+self.margin)

        
ranking_loss = my_margin_ranking_loss()
output = ranking_loss(input_one, input_two, target)
output.backward()

print('input one: ', input_one)
print('input two: ', input_two)
print('target: ', target)
print('output: ', output)

NameError: name 'input_one' is not defined

In [10]:
##ex code using marginrankingloss (pytorch) --> pairwise LF
input_one = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]], dtype=torch.float16,requires_grad=True)
input_two = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]], dtype=torch.float16,requires_grad=True)
target = torch.randn(1)

ranking_loss = nn.MarginRankingLoss()
output = ranking_loss(input_one, input_two, target)
output.backward()

print('input one: ', input_one)
print('input two: ', input_two)
print('target: ', target)
print('output: ', output)

##ex code using contrastive loss (tf)
a = tf.constant([[1, 2],
                [3, 4],
                [5, 6]], dtype=tf.float16)
b = tf.constant([[5, 9],
                [3, 6],
                [1, 8]], dtype=tf.float16)
y_pred = tf.linalg.norm(a - b, axis=1)

target = tf.random.normal([3],dtype=tf.float16)

print('input one: ', a)
print('input two: ', b)
print('target: ', target)

output = tfa.losses.contrastive_loss(target, y_pred, target)

print('output: ', output)

input one:  tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16, requires_grad=True)
input two:  tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float16, requires_grad=True)
target:  tensor([0.8661])
output:  tensor(0., grad_fn=<MeanBackward0>)
input one:  tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
input two:  tf.Tensor(
[[5. 9.]
 [3. 6.]
 [1. 8.]], shape=(3, 2), dtype=float16)
target:  tf.Tensor([ 0.7173 -1.75   -0.6577], shape=(3,), dtype=float16)
output:  tf.Tensor([ 46.62  -7.   -13.16], shape=(3,), dtype=float16)


In [42]:
##Define lossI constructed in tensorflowd
def loss(margin):
    """Provides 'constrastive_loss' an enclosing scope with variable 'margin'.

    Arguments:
        margin: Integer, defines the baseline for distance for which pairs
                should be classified as dissimilar. - (default is 1).

    Returns:
        'constrastive_loss' function with data ('margin') attached.
    """

    # Contrastive loss = mean( (1-true_value) * square(prediction) +
    #                         true_value * square( max(margin-prediction, 0) ))
    def contrastive_loss(x1, x2,y):
        """Calculates the constrastive loss.

        Arguments:
            y_true: List of labels, each label is of type float32.
            y_pred: List of predictions of same length as of y_true,
                    each label is of type float32.

        Returns:
            A tensor containing constrastive loss as floating point value.
        """
        #is this supposed to be a dot so that margin can be a scalar?
        #from trial-and-error, it appears that you need to take the mean
        # of these values.... ohhhhh, is 20 the batch size??
        my_loss = tf.math.reduce_mean(tf.maximum(0,-y*(x1-x2)+margin))
        return my_loss

    return contrastive_loss

In [43]:
##ex code using marginrankingloss (pytorch) --> pairwise LF
input_one = torch.tensor([[1, 2]], dtype=torch.float16,requires_grad=True)
input_two = torch.tensor([[5,9]], dtype=torch.float16,requires_grad=True)
print(input_one.size())
#create a target constructed in same manner as was done in implemented
#paper 
target = torch.ones(input_one.size())

ranking_loss = nn.MarginRankingLoss()
output = ranking_loss(input_one, input_two, target)
output.backward()

print('input one: ', input_one)
print('input two: ', input_two)
print('target: ', target)
print('output: ', output)

##ex code using my version of margin ranking loss (tf)
a = tf.constant([[1, 2]], dtype=tf.float16)
b = tf.constant([[5, 9]], dtype=tf.float16)

#create a target constructed in same manner as was done in implemented
#paper 
target = tf.ones(tf.shape(a),dtype=tf.float16)

print('input one: ', a)
print('input two: ', b)
print('target: ', target)

#define instance of the loss I created
#set margin = 0 bc that's what is set by default for MarginRankingLoss
my_loss = loss(0)

#set inputs to be same as inputs to MarginRankingLoss
output = my_loss(a, b, target)

print('output: ', output)

torch.Size([1, 2])
input one:  tensor([[1., 2.]], dtype=torch.float16, requires_grad=True)
input two:  tensor([[5., 9.]], dtype=torch.float16, requires_grad=True)
target:  tensor([[1., 1.]])
output:  tensor(5.5000, grad_fn=<MeanBackward0>)
input one:  tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float16)
input two:  tf.Tensor([[5. 9.]], shape=(1, 2), dtype=float16)
target:  tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float16)
output:  tf.Tensor(5.5, shape=(), dtype=float16)


##margin ranking loss notes
article that describes it: https://onlinelibrary.wiley.com/doi/full/10.1002/cav.2036?casa_token=5j5gkFZ5Te4AAAAA%3ADCeRn-ImeC_IdPHnBafYDXoD9GK82y9zCQzaWAL9Unxdus6Sfygd12JYzHJw4XDlVZG1jaafu-_IfFI

Three inputs the loss function according to the Paper we are implementing:
- gold summary: should have the highest matching score
- Candidate summary:one of two candidate summaries.I don't think we're supposed to know at this stage where the summary is being put into the loss function, what the better summary is. I think the loss function is somehow supposed to determinethat this is better period
- Worse candidate summary: one of the two candidate summaries. I think, again, that the loss function is supposed to be what determines that this is the worst candidate summary.


He is the score obtainedfrom the prediction vector. And the codes that we have, I thinkthis is from the variable "score". 
XI appears to be the index associated with the ground truth label ofthe document.


The article below describes the positive sample as the gold summary and the negative sample as the silver summary.This, to me, suggests thatthe paper which we are examiningwould follow a similar protocol. 
https://arxiv.org/pdf/2108.11846.pdf

I therefore revise my proposition of the inputs to the loss function to be the following: 
- gold summary (positive sample): should have the highest matching score
- Candidate summary (negative sample):one of two candidate summaries.

Quote from paper:
"However, there might exist a low-quality candidate that gets a higher score S. It is termed as
“silver summary” when it is picked up as the output
summary. The silver summary can be attributed to
the discrepancy problem since the seq2seq model is
only able to observe the gold summary at the time
of training while the model needs to assess a large
number of unseen alternatives at the time of inference. This problem is well-known as “exposure
bias”."

The paper suggests that the goal of usingcontrastive loss in the form of margin ranking loss is to explicitly decrease the score S of the silver summary during training.

They seemed to argue that margin ranking lossworks to ensure that the positive score, IE, the score for the golden summary, is above that of the negative score, IE, the candidate summary.

Loss = max(0,S(y_hat|X)-S(Y|X)+gamma)
where gamma = margin value (distance apart we want the gold summary to be from the candidate summary)
S(y_hat|X) = score from golden summary
S(y|X) = silver summary

Quote below is from the link below:
https://arxiv.org/pdf/2104.09061.pdf
" We add a margin ranking loss term LRANK
to encourage the model to assign higher probability
to the positive than the negative candidate." 